# Broadcasting

In [18]:
import numpy as np

In [21]:
a=np.arange(5)
print(a)
print(a.size)
print(a.shape)

[0 1 2 3 4]
5
(5,)


In [22]:
b=2

In [23]:
np.add(a,b)

array([2, 3, 4, 5, 6])

[2,2,2,2,2]

[a0+b0,a1+b1,a2+b2...]


In [31]:
a=np.random.randint(1,10,size=(2,2))
print(a.shape)
print(a.size)

(2, 2)
4


In [33]:
b=np.random.randint(11,30,size=(1,2))
print(b.shape)
print(b.size)

(1, 2)
2


In [29]:
np.add(a,b)


array([[21, 22],
       [22, 27]])