# Numpy Array Operations

### np.newaxis

In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4]
numpy_arr=np.array(list1)

In [3]:
type(numpy_arr)

numpy.ndarray

In [4]:
type(list1)

list

In [6]:
numpy_arr.shape

(4,)

In [7]:
row_vector = numpy_arr[:,np.newaxis]

In [8]:
row_vector.shape

(4, 1)

In [9]:
print(numpy_arr)

[1 2 3 4]


In [10]:
print(row_vector)

[[1]
 [2]
 [3]
 [4]]


In [11]:
col_vector = numpy_arr[np.newaxis,:]

In [12]:
col_vector.shape

(1, 4)

In [13]:
print(col_vector)

[[1 2 3 4]]


### Reshape

In [14]:
arr=np.arange(15)

In [18]:
print(arr)
print(arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
1


In [16]:
arr2d = arr.reshape(3,5)

In [17]:
print(arr2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
arr2d.ndim

2

### Arithmetic Operation On Numpy Array

In [21]:
arr1 = np.random.randint(1,10,size=(3,3))

In [22]:
print(arr1)

[[4 5 8]
 [8 4 1]
 [2 8 6]]


In [23]:
arr2 = np.random.randint(10,20,size=(3,3))

In [24]:
print(arr2)

[[15 13 15]
 [11 14 12]
 [19 15 19]]


In [25]:
np.add(arr1,arr2)

array([[19, 18, 23],
       [19, 18, 13],
       [21, 23, 25]])

In [27]:
np.subtract(arr1,arr2)

array([[-11,  -8,  -7],
       [ -3, -10, -11],
       [-17,  -7, -13]])

In [28]:
np.multiply(arr1,arr2)

array([[ 60,  65, 120],
       [ 88,  56,  12],
       [ 38, 120, 114]])

In [29]:
np.divide(arr1,arr2)

array([[0.26666667, 0.38461538, 0.53333333],
       [0.72727273, 0.28571429, 0.08333333],
       [0.10526316, 0.53333333, 0.31578947]])

In [31]:
np.dot(arr1,arr2)

array([[0, 0, 5],
       [0, 0, 4],
       [0, 0, 8]])

#### x1*x2-5*x2 + 30

In [32]:
ansArr=arr1*arr2-5*arr2 + 30

In [33]:
print(ansArr)

[[30 30 30]
 [30 30 26]
 [30 30 30]]
