# Slicing & Indexing

In [18]:
import numpy as np

In [21]:
arr1d=np.arange(10)

In [22]:
print(arr1d)

[0 1 2 3 4 5 6 7 8 9]


### Extract Even Numbers from arr1d

In [33]:
even=arr1d[:10:3]

In [34]:
print(even)

[0 3 6 9]


Indexing

In [35]:
arr1d[3]

3

In [36]:
arr1d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [37]:
arr1d[-1]

9

In [38]:
arr1d[-2]

8

In [39]:
arr1d[-3]

7

### Multidimensional Slicing and Indexing

In [96]:
arr2d=np.random.randint(30,100,size=(2,3,4))

In [97]:
print(arr2d)

[[[38 37 98 46]
  [84 57 82 56]
  [68 36 56 94]]

 [[41 46 93 89]
  [88 50 39 74]
  [98 89 92 42]]]


In [98]:
arr2d.ndim

3

In [89]:
arr2d[1:]

array([[34, 44]])

In [90]:
arr2d[0:2,0:1]

array([[42],
       [34]])

In [95]:
arr2d[-1][-1]

44