# UPCASTING & DOWNCASTING

In [2]:
import numpy as np

In [3]:
intArray = np.arange(6)

In [4]:
print(intArray)

[0 1 2 3 4 5]


In [6]:
intArray.dtype

dtype('int32')

In [7]:
floatArray=np.random.uniform(0,5,5)

In [8]:
print(floatArray)

[0.3815538  2.8691374  1.2475049  2.75369843 1.93123547]


In [9]:
floatArray.dtype

dtype('float64')

In [11]:
concatArray=np.concatenate((floatArray,intArray))

In [12]:
print(concatArray)

[0.3815538  2.8691374  1.2475049  2.75369843 1.93123547 0.
 1.         2.         3.         4.         5.        ]


In [13]:
concatArray.dtype

dtype('float64')

In [16]:
downCast=concatArray.astype('int64')

In [17]:
print(downCast)

[0 2 1 2 1 0 1 2 3 4 5]


In [18]:
downCast.dtype

dtype('int64')