# Vectorization

In [1]:
import numpy as np

In [19]:
a = np.arange(0,5)
print(a)

[0 1 2 3 4]


In [20]:
b=np.arange(5,10)
print(b)

[5 6 7 8 9]


In [13]:

res=[]
for i in range(len(a)):
    res.append(a[i]+b[i])
%timeit np.array(res)    

1.87 µs ± 136 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%timeit a + b


738 ns ± 49.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [21]:
a * b

array([ 0,  6, 14, 24, 36])

In [22]:
a / b

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [23]:
c = [0,1,2,3,4]
d = [5,6,7,8,9]
c + d

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]